//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRoleAds
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class contosoadsg4Entities1 : DbContext
    {
        public contosoadsg4Entities1()
            : base("name=contosoadsg4Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<TbComment> TbComments { get; set; }
        public virtual DbSet<TbPost> TbPosts { get; set; }
        public virtual DbSet<TbRating> TbRatings { get; set; }
        public virtual DbSet<TbSubcribePost> TbSubcribePosts { get; set; }
        public virtual DbSet<TbSubcribeUser> TbSubcribeUsers { get; set; }
        public virtual DbSet<TbUser> TbUsers { get; set; }
    }
}
