//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRoleAds
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TbComment()
        {
            this.TbComment1 = new HashSet<TbComment>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int UserId { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TbComment> TbComment1 { get; set; }
        public virtual TbComment TbComment2 { get; set; }
        public virtual TbUser TbUser { get; set; }
    }
}
